development: &default
  adapter: postgresql
  encoding: unicode
  database: getoutofnyc-rails_development
  pool: 5
  username: postgres
  password: <%= ENV['GETOUTOFNYC-RAILS_DATABASE_PASSWORD'] %>
  host: db

test:
  <<: *default
  database: getoutofnyc-rails_test

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: getoutofnyc
  username: getoutofnyc
  password: <%= ENV['GETOUTOFNYC-RAILS_DATABASE_PASSWORD'] %>
  host: aa1wnfoa5vacmfw.c8plrwqkyfst.us-east-1.rds.amazonaws.com
  port: 5432