development: &default
  adapter: postgresql
  encoding: unicode
  database: getoutofnyc-rails_development
  pool: 7
  username: postgres
  password: <%= ENV['GETOUTOFNYC_RAILS_DATABASE_PASSWORD'] %>
  # host: db

test:
  <<: *default
  database: getoutofnyc-rails_test

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: getoutofnyc
  username: getoutofnyc
  password: <%= ENV['GETOUTOFNYC_RAILS_DATABASE_PASSWORD'] %>
  port: 5432